
// Maps Atlas Slot IDs (from utils/textures.ts) to file paths relative to public/assets/textures/
// Example: 0: "blocks/dirt.png"

export const TEXTURE_PATHS: Record<number, string> = {
    // --- BLOCKS ---
    0: 'blocks/dirt.png',
    1: 'blocks/grass_top.png',
    2: 'blocks/stone.png',
    3: 'blocks/dirt.png', // Soil (if used)
    4: 'blocks/leaves_oak.png',
    5: 'blocks/sand.png',
    6: 'blocks/bedrock.png',
    7: 'blocks/log_oak.png',
    8: 'blocks/planks_oak.png',
    9: 'blocks/brick.png',
    10: 'blocks/cobblestone.png',
    11: 'blocks/glass.png',
    12: 'blocks/grass_side.png',
    13: 'blocks/log_oak_top.png',
    14: 'blocks/water.png',
    15: 'blocks/coal_ore.png',
    16: 'blocks/iron_ore.png',
    17: 'blocks/lava.png',
    18: 'blocks/sandstone_side.png',
    19: 'blocks/snow.png',
    20: 'blocks/ice.png',
    21: 'blocks/cactus_side.png',
    22: 'blocks/dead_bush.png',
    23: 'blocks/log_spruce.png',
    24: 'blocks/leaves_spruce.png',
    25: 'blocks/grass_snow_side.png',
    26: 'blocks/obsidian.png',
    27: 'blocks/planks_spruce.png',
    28: 'blocks/sandstone_top.png',
    29: 'blocks/grass_plant.png',
    30: 'blocks/rose.png',
    31: 'blocks/dandelion.png',
    
    // --- ITEMS ---
    32: 'items/wood_pickaxe.png',
    33: 'items/stone_pickaxe.png',
    34: 'items/iron_pickaxe.png',
    35: 'items/stick.png',
    36: 'items/wood_axe.png',
    37: 'items/stone_axe.png',
    38: 'items/iron_axe.png',
    39: 'items/wood_shovel.png',
    40: 'items/stone_shovel.png',
    41: 'items/iron_shovel.png',
    48: 'items/coal.png',
    49: 'items/iron_ingot.png',
    50: 'items/apple.png',
    51: 'items/oak_sapling.png',
    55: 'items/raw_iron.png',
    57: 'items/charcoal.png',
    59: 'items/raw_copper.png',
    60: 'items/copper_ingot.png',
    61: 'items/copper_pickaxe.png',
    62: 'items/copper_axe.png',
    63: 'items/copper_shovel.png',
    67: 'items/bed.png',
    73: 'items/wheat_seeds.png',
    100: 'items/raw_gold.png',
    101: 'items/gold_ingot.png',
    102: 'items/diamond.png',
    103: 'items/emerald.png',
    104: 'items/lapis_lazuli.png',
    105: 'items/wood_sword.png',
    106: 'items/wood_hoe.png',
    107: 'items/stone_sword.png',
    108: 'items/stone_hoe.png',
    109: 'items/iron_sword.png',
    110: 'items/iron_hoe.png',
    111: 'items/copper_sword.png',
    112: 'items/copper_hoe.png',
    113: 'items/gold_pickaxe.png',
    114: 'items/gold_axe.png',
    115: 'items/gold_shovel.png',
    116: 'items/gold_sword.png',
    117: 'items/gold_hoe.png',
    118: 'items/diamond_pickaxe.png',
    119: 'items/diamond_axe.png',
    120: 'items/diamond_shovel.png',
    121: 'items/diamond_sword.png',
    122: 'items/diamond_hoe.png',
    146: 'items/spruce_sapling.png',
    147: 'items/birch_sapling.png',
    148: 'items/cherry_sapling.png',
    151: 'items/iron_helmet.png',
    152: 'items/iron_chestplate.png',
    153: 'items/iron_leggings.png',
    154: 'items/iron_boots.png',
    155: 'items/polarity_boots.png',
    157: 'items/gold_helmet.png',
    158: 'items/gold_chestplate.png',
    159: 'items/gold_leggings.png',
    160: 'items/gold_boots.png',
    161: 'items/diamond_helmet.png',
    162: 'items/diamond_chestplate.png',
    163: 'items/diamond_leggings.png',
    164: 'items/diamond_boots.png',
    165: 'items/copper_helmet.png',
    166: 'items/copper_chestplate.png',
    167: 'items/copper_leggings.png',
    168: 'items/copper_boots.png',
    
    // --- UTILITY ---
    72: 'blocks/debug.png',

    // --- MAGNETISM BLOCKS ---
    149: 'blocks/positive_magnet.png',
    150: 'blocks/negative_magnet.png',
    156: 'blocks/iron_block.png',

    // --- BIOME SURFACE BLOCKS (Task ID 5) ---
    // Grass-topped pairs: top = even slot, side = top+1.
    170: 'blocks/mossy_grass_top.png',
    171: 'blocks/mossy_grass_side.png',
    172: 'blocks/lush_grass_top.png',
    173: 'blocks/lush_grass_side.png',
    174: 'blocks/dark_grass_top.png',
    175: 'blocks/dark_grass_side.png',
    176: 'blocks/meadow_grass_top.png',
    177: 'blocks/meadow_grass_side.png',
    178: 'blocks/savanna_grass_top.png',
    179: 'blocks/savanna_grass_side.png',
    180: 'blocks/jungle_grass_top.png',
    181: 'blocks/jungle_grass_side.png',
    182: 'blocks/podzol_top.png',
    183: 'blocks/podzol_side.png',
    184: 'blocks/andesite.png',
    185: 'blocks/diorite.png',
    186: 'blocks/granite.png',
    187: 'blocks/coarse_dirt.png',
    188: 'blocks/mud.png',
    189: 'blocks/mossy_cobblestone.png',

    // --- NEW WOOD FAMILIES (Task ID 6): Jungle, Dark Oak, Acacia ---
    190: 'blocks/jungle_log_top.png',
    191: 'blocks/jungle_log_side.png',
    192: 'blocks/jungle_planks.png',
    193: 'blocks/jungle_leaves.png',
    194: 'blocks/jungle_sapling.png',
    195: 'blocks/dark_oak_log_top.png',
    196: 'blocks/dark_oak_log_side.png',
    197: 'blocks/dark_oak_planks.png',
    198: 'blocks/dark_oak_leaves.png',
    199: 'blocks/dark_oak_sapling.png',
    200: 'blocks/acacia_log_top.png',
    201: 'blocks/acacia_log_side.png',
    202: 'blocks/acacia_planks.png',
    203: 'blocks/acacia_leaves.png',
    204: 'blocks/acacia_sapling.png',
};
