// Generated by scripts/build-storage-codec.mjs. Edit the TypeScript source.
"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/systems/world/storage/contentCodec.ts
var contentCodec_exports = {};
__export(contentCodec_exports, {
  decodeBlockPalette: () => decodeBlockPalette,
  decodeItemStack: () => decodeItemStack,
  encodeBlockPalette: () => encodeBlockPalette,
  encodeItemStack: () => encodeItemStack,
  upgradeLegacyBlocks: () => upgradeLegacyBlocks
});
module.exports = __toCommonJS(contentCodec_exports);

// src/types.ts
var BlockType = /* @__PURE__ */ ((BlockType2) => {
  BlockType2[BlockType2["AIR"] = 0] = "AIR";
  BlockType2[BlockType2["UNKNOWN"] = 65535] = "UNKNOWN";
  BlockType2[BlockType2["SAPLING"] = 113] = "SAPLING";
  BlockType2[BlockType2["SPRUCE_SAPLING"] = 146] = "SPRUCE_SAPLING";
  BlockType2[BlockType2["BIRCH_SAPLING"] = 147] = "BIRCH_SAPLING";
  BlockType2[BlockType2["CHERRY_SAPLING"] = 148] = "CHERRY_SAPLING";
  BlockType2[BlockType2["JUNGLE_SAPLING"] = 227] = "JUNGLE_SAPLING";
  BlockType2[BlockType2["DARK_OAK_SAPLING"] = 233] = "DARK_OAK_SAPLING";
  BlockType2[BlockType2["ACACIA_SAPLING"] = 239] = "ACACIA_SAPLING";
  BlockType2[BlockType2["DIRT"] = 1] = "DIRT";
  BlockType2[BlockType2["GRASS"] = 2] = "GRASS";
  BlockType2[BlockType2["STONE"] = 3] = "STONE";
  BlockType2[BlockType2["LEAVES"] = 5] = "LEAVES";
  BlockType2[BlockType2["SAND"] = 6] = "SAND";
  BlockType2[BlockType2["WATER"] = 7] = "WATER";
  BlockType2[BlockType2["BEDROCK"] = 8] = "BEDROCK";
  BlockType2[BlockType2["LOG"] = 9] = "LOG";
  BlockType2[BlockType2["OAK_PLANKS"] = 10] = "OAK_PLANKS";
  BlockType2[BlockType2["BRICK"] = 11] = "BRICK";
  BlockType2[BlockType2["COBBLESTONE"] = 12] = "COBBLESTONE";
  BlockType2[BlockType2["GLASS"] = 13] = "GLASS";
  BlockType2[BlockType2["COAL_ORE"] = 14] = "COAL_ORE";
  BlockType2[BlockType2["IRON_ORE"] = 15] = "IRON_ORE";
  BlockType2[BlockType2["CRAFTING_TABLE"] = 16] = "CRAFTING_TABLE";
  BlockType2[BlockType2["FURNACE"] = 17] = "FURNACE";
  BlockType2[BlockType2["FURNACE_ACTIVE"] = 18] = "FURNACE_ACTIVE";
  BlockType2[BlockType2["CHEST"] = 19] = "CHEST";
  BlockType2[BlockType2["TORCH"] = 20] = "TORCH";
  BlockType2[BlockType2["COPPER_ORE"] = 21] = "COPPER_ORE";
  BlockType2[BlockType2["LAVA"] = 22] = "LAVA";
  BlockType2[BlockType2["WOOL"] = 23] = "WOOL";
  BlockType2[BlockType2["BED_FOOT"] = 24] = "BED_FOOT";
  BlockType2[BlockType2["BED_HEAD"] = 25] = "BED_HEAD";
  BlockType2[BlockType2["OBSIDIAN"] = 26] = "OBSIDIAN";
  BlockType2[BlockType2["SANDSTONE"] = 27] = "SANDSTONE";
  BlockType2[BlockType2["SNOW_BLOCK"] = 28] = "SNOW_BLOCK";
  BlockType2[BlockType2["ICE"] = 29] = "ICE";
  BlockType2[BlockType2["CACTUS"] = 30] = "CACTUS";
  BlockType2[BlockType2["DEAD_BUSH"] = 31] = "DEAD_BUSH";
  BlockType2[BlockType2["SPRUCE_LOG"] = 32] = "SPRUCE_LOG";
  BlockType2[BlockType2["SPRUCE_LEAVES"] = 33] = "SPRUCE_LEAVES";
  BlockType2[BlockType2["SNOWY_GRASS"] = 34] = "SNOWY_GRASS";
  BlockType2[BlockType2["SPRUCE_PLANKS"] = 35] = "SPRUCE_PLANKS";
  BlockType2[BlockType2["GRASS_PLANT"] = 36] = "GRASS_PLANT";
  BlockType2[BlockType2["ROSE"] = 37] = "ROSE";
  BlockType2[BlockType2["DANDELION"] = 38] = "DANDELION";
  BlockType2[BlockType2["DEBUG_CROSS"] = 39] = "DEBUG_CROSS";
  BlockType2[BlockType2["CHERRY_LOG"] = 40] = "CHERRY_LOG";
  BlockType2[BlockType2["CHERRY_LEAVES"] = 41] = "CHERRY_LEAVES";
  BlockType2[BlockType2["CHERRY_PLANKS"] = 42] = "CHERRY_PLANKS";
  BlockType2[BlockType2["PINK_FLOWER"] = 86] = "PINK_FLOWER";
  BlockType2[BlockType2["RED_SAND"] = 43] = "RED_SAND";
  BlockType2[BlockType2["RED_SANDSTONE"] = 44] = "RED_SANDSTONE";
  BlockType2[BlockType2["TERRACOTTA"] = 45] = "TERRACOTTA";
  BlockType2[BlockType2["TERRACOTTA_YELLOW"] = 46] = "TERRACOTTA_YELLOW";
  BlockType2[BlockType2["TERRACOTTA_RED"] = 47] = "TERRACOTTA_RED";
  BlockType2[BlockType2["TERRACOTTA_WHITE"] = 91] = "TERRACOTTA_WHITE";
  BlockType2[BlockType2["TERRACOTTA_ORANGE"] = 92] = "TERRACOTTA_ORANGE";
  BlockType2[BlockType2["TERRACOTTA_MAGENTA"] = 93] = "TERRACOTTA_MAGENTA";
  BlockType2[BlockType2["TERRACOTTA_LIGHT_GRAY"] = 94] = "TERRACOTTA_LIGHT_GRAY";
  BlockType2[BlockType2["TERRACOTTA_BROWN"] = 95] = "TERRACOTTA_BROWN";
  BlockType2[BlockType2["BASALT"] = 48] = "BASALT";
  BlockType2[BlockType2["MAGMA"] = 49] = "MAGMA";
  BlockType2[BlockType2["BIRCH_LOG"] = 87] = "BIRCH_LOG";
  BlockType2[BlockType2["BIRCH_LEAVES"] = 88] = "BIRCH_LEAVES";
  BlockType2[BlockType2["BIRCH_PLANKS"] = 89] = "BIRCH_PLANKS";
  BlockType2[BlockType2["GOLD_ORE"] = 96] = "GOLD_ORE";
  BlockType2[BlockType2["DIAMOND_ORE"] = 97] = "DIAMOND_ORE";
  BlockType2[BlockType2["LAPIS_ORE"] = 98] = "LAPIS_ORE";
  BlockType2[BlockType2["EMERALD_ORE"] = 99] = "EMERALD_ORE";
  BlockType2[BlockType2["OAK_SLAB"] = 149] = "OAK_SLAB";
  BlockType2[BlockType2["SPRUCE_SLAB"] = 150] = "SPRUCE_SLAB";
  BlockType2[BlockType2["BIRCH_SLAB"] = 151] = "BIRCH_SLAB";
  BlockType2[BlockType2["CHERRY_SLAB"] = 152] = "CHERRY_SLAB";
  BlockType2[BlockType2["COBBLESTONE_SLAB"] = 153] = "COBBLESTONE_SLAB";
  BlockType2[BlockType2["STONE_SLAB"] = 154] = "STONE_SLAB";
  BlockType2[BlockType2["SANDSTONE_SLAB"] = 155] = "SANDSTONE_SLAB";
  BlockType2[BlockType2["RED_SANDSTONE_SLAB"] = 156] = "RED_SANDSTONE_SLAB";
  BlockType2[BlockType2["BRICK_SLAB"] = 157] = "BRICK_SLAB";
  BlockType2[BlockType2["OAK_STAIRS"] = 158] = "OAK_STAIRS";
  BlockType2[BlockType2["SPRUCE_STAIRS"] = 159] = "SPRUCE_STAIRS";
  BlockType2[BlockType2["BIRCH_STAIRS"] = 160] = "BIRCH_STAIRS";
  BlockType2[BlockType2["CHERRY_STAIRS"] = 161] = "CHERRY_STAIRS";
  BlockType2[BlockType2["COBBLESTONE_STAIRS"] = 162] = "COBBLESTONE_STAIRS";
  BlockType2[BlockType2["STONE_STAIRS"] = 163] = "STONE_STAIRS";
  BlockType2[BlockType2["SANDSTONE_STAIRS"] = 164] = "SANDSTONE_STAIRS";
  BlockType2[BlockType2["RED_SANDSTONE_STAIRS"] = 165] = "RED_SANDSTONE_STAIRS";
  BlockType2[BlockType2["BRICK_STAIRS"] = 166] = "BRICK_STAIRS";
  BlockType2[BlockType2["POSITIVE_MAGNET"] = 190] = "POSITIVE_MAGNET";
  BlockType2[BlockType2["NEGATIVE_MAGNET"] = 191] = "NEGATIVE_MAGNET";
  BlockType2[BlockType2["IRON_BLOCK"] = 197] = "IRON_BLOCK";
  BlockType2[BlockType2["PACKED_ICE"] = 210] = "PACKED_ICE";
  BlockType2[BlockType2["MOSSY_GRASS"] = 211] = "MOSSY_GRASS";
  BlockType2[BlockType2["LUSH_GRASS"] = 212] = "LUSH_GRASS";
  BlockType2[BlockType2["DARK_GRASS"] = 213] = "DARK_GRASS";
  BlockType2[BlockType2["MEADOW_GRASS"] = 214] = "MEADOW_GRASS";
  BlockType2[BlockType2["SAVANNA_GRASS"] = 215] = "SAVANNA_GRASS";
  BlockType2[BlockType2["JUNGLE_GRASS"] = 216] = "JUNGLE_GRASS";
  BlockType2[BlockType2["PODZOL"] = 217] = "PODZOL";
  BlockType2[BlockType2["ANDESITE"] = 218] = "ANDESITE";
  BlockType2[BlockType2["DIORITE"] = 219] = "DIORITE";
  BlockType2[BlockType2["GRANITE"] = 220] = "GRANITE";
  BlockType2[BlockType2["COARSE_DIRT"] = 221] = "COARSE_DIRT";
  BlockType2[BlockType2["MUD"] = 222] = "MUD";
  BlockType2[BlockType2["MOSSY_COBBLESTONE"] = 223] = "MOSSY_COBBLESTONE";
  BlockType2[BlockType2["JUNGLE_LOG"] = 224] = "JUNGLE_LOG";
  BlockType2[BlockType2["JUNGLE_LEAVES"] = 225] = "JUNGLE_LEAVES";
  BlockType2[BlockType2["JUNGLE_PLANKS"] = 226] = "JUNGLE_PLANKS";
  BlockType2[BlockType2["JUNGLE_SLAB"] = 228] = "JUNGLE_SLAB";
  BlockType2[BlockType2["JUNGLE_STAIRS"] = 229] = "JUNGLE_STAIRS";
  BlockType2[BlockType2["DARK_OAK_LOG"] = 230] = "DARK_OAK_LOG";
  BlockType2[BlockType2["DARK_OAK_LEAVES"] = 231] = "DARK_OAK_LEAVES";
  BlockType2[BlockType2["DARK_OAK_PLANKS"] = 232] = "DARK_OAK_PLANKS";
  BlockType2[BlockType2["DARK_OAK_SLAB"] = 234] = "DARK_OAK_SLAB";
  BlockType2[BlockType2["DARK_OAK_STAIRS"] = 235] = "DARK_OAK_STAIRS";
  BlockType2[BlockType2["ACACIA_LOG"] = 236] = "ACACIA_LOG";
  BlockType2[BlockType2["ACACIA_LEAVES"] = 237] = "ACACIA_LEAVES";
  BlockType2[BlockType2["ACACIA_PLANKS"] = 238] = "ACACIA_PLANKS";
  BlockType2[BlockType2["ACACIA_SLAB"] = 240] = "ACACIA_SLAB";
  BlockType2[BlockType2["ACACIA_STAIRS"] = 241] = "ACACIA_STAIRS";
  BlockType2[BlockType2["MAGNETITE_BLOCK"] = 242] = "MAGNETITE_BLOCK";
  BlockType2[BlockType2["POSITIVE_MAGNETITE_CRYSTAL"] = 243] = "POSITIVE_MAGNETITE_CRYSTAL";
  BlockType2[BlockType2["NEGATIVE_MAGNETITE_CRYSTAL"] = 244] = "NEGATIVE_MAGNETITE_CRYSTAL";
  BlockType2[BlockType2["MAGNETIC_SPIKE"] = 245] = "MAGNETIC_SPIKE";
  BlockType2[BlockType2["MAGNETIC_BOSS_SUMMONER"] = 246] = "MAGNETIC_BOSS_SUMMONER";
  BlockType2[BlockType2["MAGNETIC_SHIELD_CRYSTAL"] = 247] = "MAGNETIC_SHIELD_CRYSTAL";
  BlockType2[BlockType2["CHARGED_MAGNETITE"] = 248] = "CHARGED_MAGNETITE";
  BlockType2[BlockType2["MAGNETITE_SHARD"] = 249] = "MAGNETITE_SHARD";
  BlockType2[BlockType2["MAGNETITE_SLAB"] = 250] = "MAGNETITE_SLAB";
  BlockType2[BlockType2["MAGNETITE_STAIRS"] = 251] = "MAGNETITE_STAIRS";
  BlockType2[BlockType2["MAGNETITE_BRICKS"] = 252] = "MAGNETITE_BRICKS";
  BlockType2[BlockType2["MAGNETITE_BRICK_SLAB"] = 253] = "MAGNETITE_BRICK_SLAB";
  BlockType2[BlockType2["MAGNETITE_BRICK_STAIRS"] = 254] = "MAGNETITE_BRICK_STAIRS";
  BlockType2[BlockType2["CHISELED_MAGNETITE"] = 255] = "CHISELED_MAGNETITE";
  BlockType2[BlockType2["DEEPSLATE"] = 50] = "DEEPSLATE";
  BlockType2[BlockType2["COBBLED_DEEPSLATE"] = 51] = "COBBLED_DEEPSLATE";
  BlockType2[BlockType2["DRIPSTONE_BLOCK"] = 52] = "DRIPSTONE_BLOCK";
  BlockType2[BlockType2["POINTED_DRIPSTONE"] = 53] = "POINTED_DRIPSTONE";
  BlockType2[BlockType2["MOSS_BLOCK"] = 54] = "MOSS_BLOCK";
  BlockType2[BlockType2["GLOW_LICHEN"] = 55] = "GLOW_LICHEN";
  BlockType2[BlockType2["AMETHYST_BLOCK"] = 56] = "AMETHYST_BLOCK";
  BlockType2[BlockType2["BUDDING_AMETHYST"] = 57] = "BUDDING_AMETHYST";
  BlockType2[BlockType2["AMETHYST_CLUSTER"] = 58] = "AMETHYST_CLUSTER";
  BlockType2[BlockType2["CALCITE"] = 59] = "CALCITE";
  BlockType2[BlockType2["DEEPSLATE_COAL_ORE"] = 60] = "DEEPSLATE_COAL_ORE";
  BlockType2[BlockType2["DEEPSLATE_IRON_ORE"] = 61] = "DEEPSLATE_IRON_ORE";
  BlockType2[BlockType2["DEEPSLATE_COPPER_ORE"] = 62] = "DEEPSLATE_COPPER_ORE";
  BlockType2[BlockType2["DEEPSLATE_GOLD_ORE"] = 63] = "DEEPSLATE_GOLD_ORE";
  BlockType2[BlockType2["DEEPSLATE_DIAMOND_ORE"] = 64] = "DEEPSLATE_DIAMOND_ORE";
  BlockType2[BlockType2["DEEPSLATE_LAPIS_ORE"] = 65] = "DEEPSLATE_LAPIS_ORE";
  BlockType2[BlockType2["DEEPSLATE_EMERALD_ORE"] = 66] = "DEEPSLATE_EMERALD_ORE";
  return BlockType2;
})(BlockType || {});
((BlockType2) => {
  BlockType2.ECHO_STONE = 70;
  BlockType2.ECHO_BRICKS = 71;
  BlockType2.CRACKED_ECHO_BRICKS = 72;
  BlockType2.CHISELED_ECHO_STONE = 73;
  BlockType2.ECHO_MOSAIC = 74;
  BlockType2.ECHO_CRYSTAL = 75;
  BlockType2.RESONANCE_PYLON = 76;
  BlockType2.PULSE_CONDUIT = 78;
  BlockType2.PHASE_BLOCK = 79;
  BlockType2.RESONANCE_PLATE = 80;
  BlockType2.RESONANT_LAMP = 81;
  BlockType2.ECHO_SPIKES = 82;
  BlockType2.SENTINEL_CORE = 83;
  BlockType2.LISTENING_STONE = 84;
  BlockType2.VAULT_SEAL = 85;
  BlockType2.ECHO_STONE_SLAB = 178;
  BlockType2.ECHO_STONE_STAIRS = 179;
  BlockType2.ECHO_BRICK_SLAB = 180;
  BlockType2.ECHO_BRICK_STAIRS = 181;
})(BlockType || (BlockType = {}));

// src/systems/registry/legacyIds.ts
var LEGACY_CONTENT = [
  [0, "atlas:air", "block"],
  [1, "atlas:dirt", "block"],
  [2, "atlas:grass", "block"],
  [3, "atlas:stone", "block"],
  [4, "atlas:legacy_unknown_4", "retired"],
  [5, "atlas:leaves", "block"],
  [6, "atlas:sand", "block"],
  [7, "atlas:water", "block"],
  [8, "atlas:bedrock", "block"],
  [9, "atlas:log", "block"],
  [10, "atlas:oak_planks", "block"],
  [11, "atlas:brick", "block"],
  [12, "atlas:cobblestone", "block"],
  [13, "atlas:glass", "block"],
  [14, "atlas:coal_ore", "block"],
  [15, "atlas:iron_ore", "block"],
  [16, "atlas:crafting_table", "block"],
  [17, "atlas:furnace", "block"],
  [18, "atlas:furnace_active", "block"],
  [19, "atlas:chest", "block"],
  [20, "atlas:torch", "block"],
  [21, "atlas:copper_ore", "block"],
  [22, "atlas:lava", "block"],
  [23, "atlas:wool", "block"],
  [24, "atlas:bed_foot", "block"],
  [25, "atlas:bed_head", "block"],
  [26, "atlas:obsidian", "block"],
  [27, "atlas:sandstone", "block"],
  [28, "atlas:snow_block", "block"],
  [29, "atlas:ice", "block"],
  [30, "atlas:cactus", "block"],
  [31, "atlas:dead_bush", "block"],
  [32, "atlas:spruce_log", "block"],
  [33, "atlas:spruce_leaves", "block"],
  [34, "atlas:snowy_grass", "block"],
  [35, "atlas:spruce_planks", "block"],
  [36, "atlas:grass_plant", "block"],
  [37, "atlas:rose", "block"],
  [38, "atlas:dandelion", "block"],
  [39, "atlas:debug_cross", "block"],
  [40, "atlas:cherry_log", "block"],
  [41, "atlas:cherry_leaves", "block"],
  [42, "atlas:cherry_planks", "block"],
  [43, "atlas:red_sand", "block"],
  [44, "atlas:red_sandstone", "block"],
  [45, "atlas:terracotta", "block"],
  [46, "atlas:terracotta_yellow", "block"],
  [47, "atlas:terracotta_red", "block"],
  [48, "atlas:basalt", "block"],
  [49, "atlas:magma", "block"],
  [50, "atlas:deepslate", "block"],
  [51, "atlas:cobbled_deepslate", "block"],
  [52, "atlas:dripstone_block", "block"],
  [53, "atlas:pointed_dripstone", "block"],
  [54, "atlas:moss_block", "block"],
  [55, "atlas:glow_lichen", "block"],
  [56, "atlas:amethyst_block", "block"],
  [57, "atlas:budding_amethyst", "block"],
  [58, "atlas:amethyst_cluster", "block"],
  [59, "atlas:calcite", "block"],
  [60, "atlas:deepslate_coal_ore", "block"],
  [61, "atlas:deepslate_iron_ore", "block"],
  [62, "atlas:deepslate_copper_ore", "block"],
  [63, "atlas:deepslate_gold_ore", "block"],
  [64, "atlas:deepslate_diamond_ore", "block"],
  [65, "atlas:deepslate_lapis_ore", "block"],
  [66, "atlas:deepslate_emerald_ore", "block"],
  [67, "atlas:banana", "item"],
  [68, "atlas:lumen_berry", "item"],
  [69, "atlas:foragers_bowl", "item"],
  [70, "atlas:echo_stone", "block"],
  [71, "atlas:echo_bricks", "block"],
  [72, "atlas:cracked_echo_bricks", "block"],
  [73, "atlas:chiseled_echo_stone", "block"],
  [74, "atlas:echo_mosaic", "block"],
  [75, "atlas:echo_crystal", "block"],
  [76, "atlas:resonance_pylon", "block"],
  [77, "atlas:legacy_unknown_77", "retired"],
  [78, "atlas:pulse_conduit", "block"],
  [79, "atlas:phase_block", "block"],
  [80, "atlas:resonance_plate", "block"],
  [81, "atlas:resonant_lamp", "block"],
  [82, "atlas:echo_spikes", "block"],
  [83, "atlas:sentinel_core", "block"],
  [84, "atlas:listening_stone", "block"],
  [85, "atlas:vault_seal", "block"],
  [86, "atlas:pink_flower", "block"],
  [87, "atlas:birch_log", "block"],
  [88, "atlas:birch_leaves", "block"],
  [89, "atlas:birch_planks", "block"],
  [90, "atlas:legacy_unknown_90", "retired"],
  [91, "atlas:terracotta_white", "block"],
  [92, "atlas:terracotta_orange", "block"],
  [93, "atlas:terracotta_magenta", "block"],
  [94, "atlas:terracotta_light_gray", "block"],
  [95, "atlas:terracotta_brown", "block"],
  [96, "atlas:gold_ore", "block"],
  [97, "atlas:diamond_ore", "block"],
  [98, "atlas:lapis_ore", "block"],
  [99, "atlas:emerald_ore", "block"],
  [100, "atlas:wood_pickaxe", "item"],
  [101, "atlas:stone_pickaxe", "item"],
  [102, "atlas:iron_pickaxe", "item"],
  [103, "atlas:stick", "item"],
  [104, "atlas:wood_axe", "item"],
  [105, "atlas:stone_axe", "item"],
  [106, "atlas:iron_axe", "item"],
  [107, "atlas:wood_shovel", "item"],
  [108, "atlas:stone_shovel", "item"],
  [109, "atlas:iron_shovel", "item"],
  [110, "atlas:coal", "item"],
  [111, "atlas:iron_ingot", "item"],
  [112, "atlas:apple", "item"],
  [113, "atlas:sapling", "item"],
  [114, "atlas:raw_iron", "item"],
  [115, "atlas:charcoal", "item"],
  [116, "atlas:copper_ingot", "item"],
  [117, "atlas:raw_copper", "item"],
  [118, "atlas:copper_pickaxe", "item"],
  [119, "atlas:copper_axe", "item"],
  [120, "atlas:copper_shovel", "item"],
  [121, "atlas:bed_item", "item"],
  [122, "atlas:wheat_seeds", "item"],
  [123, "atlas:raw_gold", "item"],
  [124, "atlas:gold_ingot", "item"],
  [125, "atlas:diamond", "item"],
  [126, "atlas:lapis_lazuli", "item"],
  [127, "atlas:emerald", "item"],
  [128, "atlas:wood_sword", "item"],
  [129, "atlas:wood_hoe", "item"],
  [130, "atlas:stone_sword", "item"],
  [131, "atlas:stone_hoe", "item"],
  [132, "atlas:iron_sword", "item"],
  [133, "atlas:iron_hoe", "item"],
  [134, "atlas:gold_pickaxe", "item"],
  [135, "atlas:gold_axe", "item"],
  [136, "atlas:gold_shovel", "item"],
  [137, "atlas:gold_sword", "item"],
  [138, "atlas:gold_hoe", "item"],
  [139, "atlas:diamond_pickaxe", "item"],
  [140, "atlas:diamond_axe", "item"],
  [141, "atlas:diamond_shovel", "item"],
  [142, "atlas:diamond_sword", "item"],
  [143, "atlas:diamond_hoe", "item"],
  [144, "atlas:copper_sword", "item"],
  [145, "atlas:copper_hoe", "item"],
  [146, "atlas:spruce_sapling", "item"],
  [147, "atlas:birch_sapling", "item"],
  [148, "atlas:cherry_sapling", "item"],
  [149, "atlas:oak_slab", "block"],
  [150, "atlas:spruce_slab", "block"],
  [151, "atlas:birch_slab", "block"],
  [152, "atlas:cherry_slab", "block"],
  [153, "atlas:cobblestone_slab", "block"],
  [154, "atlas:stone_slab", "block"],
  [155, "atlas:sandstone_slab", "block"],
  [156, "atlas:red_sandstone_slab", "block"],
  [157, "atlas:brick_slab", "block"],
  [158, "atlas:oak_stairs", "block"],
  [159, "atlas:spruce_stairs", "block"],
  [160, "atlas:birch_stairs", "block"],
  [161, "atlas:cherry_stairs", "block"],
  [162, "atlas:cobblestone_stairs", "block"],
  [163, "atlas:stone_stairs", "block"],
  [164, "atlas:sandstone_stairs", "block"],
  [165, "atlas:red_sandstone_stairs", "block"],
  [166, "atlas:brick_stairs", "block"],
  [167, "atlas:polarity_boots_upgrade", "item"],
  [168, "atlas:upgraded_polarity_boots", "item"],
  [169, "atlas:boat", "item"],
  [170, "atlas:echo_shard", "item"],
  [171, "atlas:echo_dust", "item"],
  [172, "atlas:legacy_unknown_172", "retired"],
  [173, "atlas:echo_core", "item"],
  [174, "atlas:legacy_unknown_174", "retired"],
  [175, "atlas:legacy_unknown_175", "retired"],
  [176, "atlas:legacy_unknown_176", "retired"],
  [177, "atlas:fractured_core", "item"],
  [178, "atlas:echo_stone_slab", "block"],
  [179, "atlas:echo_stone_stairs", "block"],
  [180, "atlas:echo_brick_slab", "block"],
  [181, "atlas:echo_brick_stairs", "block"],
  [182, "atlas:vaultsteel_spear", "item"],
  [183, "atlas:vault_crossbow", "item"],
  [184, "atlas:vault_bolt", "item"],
  [185, "atlas:bellbreaker_maul", "item"],
  [186, "atlas:echo_tuning_fork", "item"],
  [187, "atlas:titan_hammer", "item"],
  [188, "atlas:legacy_unknown_188", "retired"],
  [189, "atlas:legacy_unknown_189", "retired"],
  [190, "atlas:positive_magnet", "block"],
  [191, "atlas:negative_magnet", "block"],
  [192, "atlas:iron_helmet", "item"],
  [193, "atlas:iron_chestplate", "item"],
  [194, "atlas:iron_leggings", "item"],
  [195, "atlas:iron_boots", "item"],
  [196, "atlas:polarity_boots", "item"],
  [197, "atlas:iron_block", "block"],
  [198, "atlas:gold_helmet", "item"],
  [199, "atlas:gold_chestplate", "item"],
  [200, "atlas:gold_leggings", "item"],
  [201, "atlas:gold_boots", "item"],
  [202, "atlas:diamond_helmet", "item"],
  [203, "atlas:diamond_chestplate", "item"],
  [204, "atlas:diamond_leggings", "item"],
  [205, "atlas:diamond_boots", "item"],
  [206, "atlas:copper_helmet", "item"],
  [207, "atlas:copper_chestplate", "item"],
  [208, "atlas:copper_leggings", "item"],
  [209, "atlas:copper_boots", "item"],
  [210, "atlas:packed_ice", "block"],
  [211, "atlas:mossy_grass", "block"],
  [212, "atlas:lush_grass", "block"],
  [213, "atlas:dark_grass", "block"],
  [214, "atlas:meadow_grass", "block"],
  [215, "atlas:savanna_grass", "block"],
  [216, "atlas:jungle_grass", "block"],
  [217, "atlas:podzol", "block"],
  [218, "atlas:andesite", "block"],
  [219, "atlas:diorite", "block"],
  [220, "atlas:granite", "block"],
  [221, "atlas:coarse_dirt", "block"],
  [222, "atlas:mud", "block"],
  [223, "atlas:mossy_cobblestone", "block"],
  [224, "atlas:jungle_log", "block"],
  [225, "atlas:jungle_leaves", "block"],
  [226, "atlas:jungle_planks", "block"],
  [227, "atlas:jungle_sapling", "item"],
  [228, "atlas:jungle_slab", "block"],
  [229, "atlas:jungle_stairs", "block"],
  [230, "atlas:dark_oak_log", "block"],
  [231, "atlas:dark_oak_leaves", "block"],
  [232, "atlas:dark_oak_planks", "block"],
  [233, "atlas:dark_oak_sapling", "item"],
  [234, "atlas:dark_oak_slab", "block"],
  [235, "atlas:dark_oak_stairs", "block"],
  [236, "atlas:acacia_log", "block"],
  [237, "atlas:acacia_leaves", "block"],
  [238, "atlas:acacia_planks", "block"],
  [239, "atlas:acacia_sapling", "item"],
  [240, "atlas:acacia_slab", "block"],
  [241, "atlas:acacia_stairs", "block"],
  [242, "atlas:magnetite_block", "block"],
  [243, "atlas:positive_magnetite_crystal", "block"],
  [244, "atlas:negative_magnetite_crystal", "block"],
  [245, "atlas:magnetic_spike", "block"],
  [246, "atlas:magnetic_boss_summoner", "block"],
  [247, "atlas:magnetic_shield_crystal", "block"],
  [248, "atlas:charged_magnetite", "block"],
  [249, "atlas:magnetite_shard", "block"],
  [250, "atlas:magnetite_slab", "block"],
  [251, "atlas:magnetite_stairs", "block"],
  [252, "atlas:magnetite_bricks", "block"],
  [253, "atlas:magnetite_brick_slab", "block"],
  [254, "atlas:magnetite_brick_stairs", "block"],
  [255, "atlas:chiseled_magnetite", "block"]
];
var LEGACY_BLOCK_KEYS = new Map(LEGACY_CONTENT.map(([id, key]) => [id, key]));
var LEGACY_ITEM_KEYS = new Map(LEGACY_CONTENT.map(([id, key]) => [id, key]));

// src/systems/registry/contentIds.ts
var blocksById = /* @__PURE__ */ new Map();
var blocksByKey = /* @__PURE__ */ new Map();
var itemsById = /* @__PURE__ */ new Map();
var itemsByKey = /* @__PURE__ */ new Map();
var blockItems = /* @__PURE__ */ new Map();
var KEY = /^[a-z0-9_.-]+:[a-z0-9_./-]+$/;
function registerBlockIdentity(id, key) {
  if (!Number.isInteger(id) || id < 0 || id > 65535 || !KEY.test(key)) throw new Error(`Invalid block identity ${key}/${id}`);
  if (blocksById.has(id) || blocksByKey.has(key)) throw new Error(`Duplicate block identity ${key}/${id}`);
  const entry = Object.freeze({ id, key });
  blocksById.set(id, entry);
  blocksByKey.set(key, entry);
}
function registerItemIdentity(id, key, placedBlock = null) {
  if (!Number.isInteger(id) || id < 0 || !KEY.test(key)) throw new Error(`Invalid item identity ${key}/${id}`);
  if (itemsById.has(id) || itemsByKey.has(key)) throw new Error(`Duplicate item identity ${key}/${id}`);
  if (placedBlock !== null && !blocksById.has(placedBlock)) throw new Error(`Item ${key} places an unregistered block`);
  const entry = Object.freeze({ id, key, placedBlock });
  itemsById.set(id, entry);
  itemsByKey.set(key, entry);
  if (placedBlock !== null) blockItems.set(placedBlock, id);
}
var SAPLING_IDS = /* @__PURE__ */ new Set([113, 146, 147, 148, 227, 233, 239]);
for (const [id, key, kind] of LEGACY_CONTENT) {
  if (kind === "block" || SAPLING_IDS.has(id)) registerBlockIdentity(id, key);
}
registerBlockIdentity(65535 /* UNKNOWN */, "atlas:unknown_block");
for (const [id, key, kind] of LEGACY_CONTENT) {
  if (kind !== "retired") registerItemIdentity(id, key, blocksById.get(id)?.id ?? null);
}
registerItemIdentity(65535 /* UNKNOWN */, "atlas:unknown_item");
var blockIdentity = (id) => blocksById.get(id);
var itemIdentity = (id) => itemsById.get(id);
var blockFromKey = (key) => blocksByKey.get(key)?.id;
var itemFromKey = (key) => itemsByKey.get(key)?.id;

// src/systems/world/storage/contentCodec.ts
var clone = (value) => structuredClone(value);
var contentKey = (key) => typeof key === "string" && key.length > 0 && key.length <= 256 && key.includes(":");
function encodeItemStack(stack) {
  if (!stack) return null;
  const key = stack.unknownKey ?? itemIdentity(stack.type)?.key ?? LEGACY_ITEM_KEYS.get(stack.type);
  if (!key) throw new Error(`Cannot save unregistered item handle ${stack.type}`);
  const copy = clone(stack);
  delete copy.unknownKey;
  return { ...copy, type: key };
}
function decodeItemStack(value) {
  if (value == null) return null;
  if (typeof value !== "object") throw new Error("Invalid saved item stack");
  const stack = value;
  if (!Number.isInteger(stack.count) || stack.count <= 0) throw new Error("Invalid saved item count");
  const key = typeof stack.type === "number" ? LEGACY_ITEM_KEYS.get(stack.type) : stack.type;
  if (!contentKey(key)) throw new Error(`Invalid saved item identity ${String(stack.type)}`);
  const id = itemFromKey(key);
  const copy = clone(stack);
  delete copy.unknownKey;
  return {
    ...copy,
    type: id ?? 65535 /* UNKNOWN */,
    count: stack.count,
    ...id === void 0 ? { unknownKey: key } : {}
  };
}
function mapEntityStacks(value, encode) {
  if (!value) return void 0;
  const output = clone(value);
  const transform = encode ? encodeItemStack : decodeItemStack;
  for (const chest of Object.values(output.chests ?? {})) {
    if (!Array.isArray(chest.items)) throw new Error("Invalid saved chest");
    chest.items = chest.items.map((stack) => transform(stack));
  }
  for (const furnace of Object.values(output.furnaces ?? {})) {
    for (const slot of ["input", "fuel", "output"]) furnace[slot] = transform(furnace[slot]);
  }
  return output;
}
function upgradeLegacyBlocks(bytes) {
  const blocks = new Uint16Array(bytes.length);
  const unknownBlocks = {};
  for (let i = 0; i < bytes.length; i++) {
    const key = LEGACY_BLOCK_KEYS.get(bytes[i]);
    const id = blockFromKey(key);
    blocks[i] = id ?? 65535 /* UNKNOWN */;
    if (id === void 0) unknownBlocks[i] = key;
  }
  return { blocks, ...Object.keys(unknownBlocks).length ? { unknownBlocks } : {} };
}
var HEADER = 16;
var MAX_CELLS = 1048576;
var MAX_DICTIONARY_BYTES = 32 * 1024 * 1024;
var encoder = new TextEncoder();
var decoder = new TextDecoder("utf-8", { fatal: true });
function encodeBlockPalette(blocks, extras = {}) {
  if (blocks.length > MAX_CELLS) throw new Error("Block volume exceeds codec limit");
  const keys = [];
  const keyIndices = /* @__PURE__ */ new Map();
  const local = new Uint16Array(blocks.length);
  const handleCache = /* @__PURE__ */ new Map();
  for (let i = 0; i < blocks.length; i++) {
    const id = blocks[i];
    let key = id === 65535 /* UNKNOWN */ ? extras.unknownBlocks?.[i] : void 0;
    if (!key) {
      key = handleCache.get(id) ?? blockIdentity(id)?.key ?? LEGACY_BLOCK_KEYS.get(id);
      if (!key) throw new Error(`Cannot save unregistered block handle ${id}`);
      handleCache.set(id, key);
    }
    if (!contentKey(key)) throw new Error("Invalid block palette key");
    let index = keyIndices.get(key);
    if (index === void 0) {
      index = keys.length;
      if (index > 65535) throw new Error("Block palette exceeds 65536 entries");
      keys.push(key);
      keyIndices.set(key, index);
    }
    local[i] = index;
  }
  const bits = keys.length <= 1 ? 0 : Math.ceil(Math.log2(keys.length));
  const dictionary = encoder.encode(JSON.stringify({ keys, tileEntities: mapEntityStacks(extras.tileEntities, true) }));
  if (dictionary.length > MAX_DICTIONARY_BYTES) throw new Error("Chunk dictionary exceeds codec limit");
  const bytes = new Uint8Array(HEADER + dictionary.length + Math.ceil(blocks.length * bits / 8));
  bytes.set([65, 84, 80, 1]);
  const view = new DataView(bytes.buffer);
  view.setUint32(4, blocks.length);
  view.setUint32(8, dictionary.length);
  bytes[12] = bits;
  bytes.set(dictionary, HEADER);
  let position = HEADER + dictionary.length;
  let accumulator = 0;
  let available = 0;
  if (bits) for (const index of local) {
    accumulator |= index << available;
    available += bits;
    while (available >= 8) {
      bytes[position++] = accumulator & 255;
      accumulator >>>= 8;
      available -= 8;
    }
  }
  if (available) bytes[position] = accumulator & 255;
  return bytes;
}
function decodeBlockPalette(bytes) {
  if (bytes.length < HEADER || bytes[0] !== 65 || bytes[1] !== 84 || bytes[2] !== 80 || bytes[3] !== 1) throw new Error("Invalid ATP1 block palette");
  const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);
  const count = view.getUint32(4);
  const dictionaryLength = view.getUint32(8);
  const bits = bytes[12];
  if (count > MAX_CELLS || dictionaryLength > MAX_DICTIONARY_BYTES || bits > 16 || bytes[13] || bytes[14] || bytes[15]) throw new Error("Invalid ATP1 palette header");
  if (bytes.length !== HEADER + dictionaryLength + Math.ceil(count * bits / 8)) throw new Error("Truncated or trailing ATP1 palette data");
  const dictionary = JSON.parse(decoder.decode(bytes.subarray(HEADER, HEADER + dictionaryLength)));
  const keys = dictionary.keys;
  if (!Array.isArray(keys) || keys.length > 65536 || count > 0 && keys.length === 0 || keys.some((key) => !contentKey(key)) || new Set(keys).size !== keys.length || bits !== (keys.length <= 1 ? 0 : Math.ceil(Math.log2(keys.length)))) throw new Error("Invalid ATP1 key dictionary");
  const palette = keys.map((key) => blockFromKey(key));
  const blocks = new Uint16Array(count);
  const unknownBlocks = {};
  let position = HEADER + dictionaryLength;
  let accumulator = 0;
  let available = 0;
  const mask = (1 << bits) - 1;
  for (let i = 0; i < count; i++) {
    while (available < bits) {
      accumulator |= bytes[position++] << available;
      available += 8;
    }
    const index = bits ? accumulator & mask : 0;
    accumulator >>>= bits;
    available -= bits;
    if (index >= keys.length) throw new Error("Invalid ATP1 palette index");
    blocks[i] = palette[index] ?? 65535 /* UNKNOWN */;
    if (palette[index] === void 0) unknownBlocks[i] = keys[index];
  }
  if (accumulator !== 0) throw new Error("Non-zero ATP1 padding");
  return {
    blocks,
    ...Object.keys(unknownBlocks).length ? { unknownBlocks } : {},
    ...dictionary.tileEntities ? { tileEntities: mapEntityStacks(dictionary.tileEntities, false) } : {}
  };
}
