export const FUTURE_SPLASH_TEASERS_A = [
    'Some worlds have no sky',
    'Not every horizon belongs to this world.',
    'The next doorway may not lead home.',
    'One world was never the plan.',
    'Somewhere, the rules are different.',
    'The world ends. The journey does not.',
    'There are places the compass cannot understand.',
    'The next world may be below, not beyond.',
    'Some portals should stay closed.',
    'The map may be missing entire worlds.',
    'Atlas has more pages.',
    'The ocean is deeper than it looks.',
    'Something built a city down there.',
    'The deepest structures were never meant to surface.',
    'The water gets heavier.',
    'The city is waiting below.',
    'Pressure is another kind of enemy.',
    'The next fight may begin before you see it.',
    'Not every boss waits in an arena.',
    'Every region has its own rules.',
    'The next guardian is already awake.',
    'One boss was only the beginning.',
    'Some victories leave scars on the world.',
    'You may need the whole region to win.',
    'The mountain moved...',
] as const;
