export const FUTURE_SPLASH_TEASERS_B = [
    'Look up...Higher.',
    'Some enemies are too large for arenas.',
    'You are standing on something.',
    'The ground has a heartbeat.',
    'Timing matters more than armor.',
    'The next enemy may fight back properly.',
    'Not everything hostile waits for night.',
    'The world is getting less empty...',
    'You are not the only one exploring.',
    'The caves will not stay quiet forever...',
    'You may finally see yourself coming.',
    'Some fights deserve a wider view...',
    'You have a body...Probably.',
    'Perspective changes everything!',
    'Gravity may have competition.',
    'You may not explore alone forever...',
    'Some worlds are too large for one inventory...',
    'The world has room for company...',
    'The Warden was guarding more than a region...',
    'Defeating one boss may wake another...',
    'Who built the altars?',
    'The bosses may know each other...',
    'Some regions are waiting to be awakened...',
    'Atlas is bigger than one world...',
] as const;
